In [5]:

pip install numpy


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [6]:
import numpy as np

In [ ]:
"""Determining the shape of a matrics"""
a = np.array([[1, 2, 3], [4, 5, 6]])

a.shape

(2, 3)

In [26]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [27]:
a[-1]

8

In [28]:
a[:3]

array([1, 2, 3])

In [17]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])


In [18]:
a[1, 3]

8

In [19]:
a.ndim

2

In [24]:
array = np.array(["1", "2", "3", "4", "5", 9])
array.dtype

dtype('<U11')

In [ ]:
test = np.array([list(range(6)), list(range(6))])
test.size

True

In [40]:
np.zeros(3)

array([0., 0., 0.])

In [39]:
np.ones(3)

array([1., 1., 1.])

In [41]:
np.empty(2)

array([0., 0.])

In [42]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [44]:
np.ones(2, dtype=np.int32)

array([1, 1])

In [60]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [46]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [49]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [50]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [52]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [54]:
z = np.concatenate((x, y), axis=0)
z.shape

(3, 2)

In [55]:
array_example = np.array(
    [
        [[0, 1, 2, 3], [4, 5, 6, 7]],
        [[0, 1, 2, 3], [4, 5, 6, 7]],
        [[0, 1, 2, 3], [4, 5, 6, 7]],
    ]
)

In [56]:
array_example.ndim

3

In [59]:
array_example.shape

(3, 2, 4)

In [62]:
array_example.reshape(4, 3, 2)

array([[[0, 1],
        [2, 3],
        [4, 5]],

       [[6, 7],
        [0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7],
        [0, 1]],

       [[2, 3],
        [4, 5],
        [6, 7]]])

In [63]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [64]:
a2 = a[np.newaxis, :]
a2

array([[1, 2, 3, 4, 5, 6]])

In [66]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)